"""Add price_per_unit column to Inventory

Revision ID: 0a0bcc3edf22
Revises: 
Create Date: 2024-02-11 01:07:32.440116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0bcc3edf22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('price_per_unit', sa.Float(), nullable=False))
    op.drop_column('inventory', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('price', sa.FLOAT(), nullable=False))
    op.drop_column('inventory', 'price_per_unit')
    # ### end Alembic commands ###
