"""Add transaction_type column to Transaction table

Revision ID: 96ec5f672bb6
Revises: 0a0bcc3edf22
Create Date: 2024-02-11 11:02:03.254945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ec5f672bb6'
down_revision = '0a0bcc3edf22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transaction_type')
    # ### end Alembic commands ###
